### ISSUE TITLE
Heatmap color palette 

### ISSUE THREAD

**Issue by bpostlethwaite** [plotly/react-plotly.js-editor#128]
use the new https://github.com/plotly/react-colorscales under the hood. test

**Comment by VeraZab** [comment]
for reference: currently what we have in plotly/create is this one:
![screen shot 2018-01-22 at 11 17 13 am](https://user-images.githubusercontent.com/4257572/35231087-d7d2896e-ff65-11e7-8690-20177d20f926.png)

@aulneau what would you say of taking a shot at this widget?

**Comment by nicolaskruchten** [comment]
Is anything more needed for this issue or can we close it? I've got the new widget in place for the heatmap now and it works great
