### ISSUE TITLE
Axes Lines and Tick Markers Folds

### ISSUE THREAD

**Issue by bpostlethwaite** [plotly/react-plotly.js-editor#132]
![image](https://user-images.githubusercontent.com/1176674/33376856-560de2f0-d4dd-11e7-87d3-74dc61c0c739.png)
![image](https://user-images.githubusercontent.com/1176674/33376870-61e17916-d4dd-11e7-98d6-90c4ef0acc0f.png)

**Comment by VeraZab** [comment]
closed in #289
