### ISSUE TITLE
Trace symbols in Trace connected containers

### ISSUE THREAD

**Issue by bpostlethwaite** [plotly/react-plotly.js-editor#139]
![image](https://user-images.githubusercontent.com/1176674/33377913-1b3d396a-d4e1-11e7-84d4-9d2ff62dad73.png)

**Comment by VeraZab** [comment]
hey, @bpostlethwaite the batch app is using only basic plot types: https://github.com/plotly/plotly.js-batch-reporter/blob/master/src/App.js#L9

is this what we want? should we try with the full plotly.js library of traces?

this also makes me think that we don't have icons for absolutely ALL plotly.js chart types, I guess we can just use a stub icon in the meanwhile, for the plot types we don't have an icon for

**Comment by bpostlethwaite** [comment]
For now it is - see https://github.com/plotly/plotly.js-batch-reporter/blob/master/src/components/CustomPanels.js#L49-L61
