### ISSUE TITLE
Shapes panel

### ISSUE THREAD

**Issue by bpostlethwaite** [plotly/react-plotly.js-editor#143]
see workspace

**Comment by VeraZab** [comment]
going to track these here: #159

**Comment by nicolaskruchten** [comment]
I'm going to implement this similar to the way Ben did the Notes panel: no dropdown menu on the +Shapes thing, it'll just be a type-switcher in the fold itself. I should be able to just reuse the Notes framework without too much issue.

**Comment by nicolaskruchten** [comment]
(reopening and self-assigning just so it ends up in my Github todo list as its own item :)
