### ISSUE TITLE
Collapse all

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/react-plotly.js-editor#153]
Copy feature from Workspace

**Comment by VeraZab** [comment]
ok, starting this one

**Comment by VeraZab** [comment]
Hmm, yeah, for TraceAccordion and Annotations accordion, Folds are not children..
unless there's something I'm not seeing..

**Comment by bpostlethwaite** [comment]
Hmmm what if Accordions are HOCs around Panels? That would change the DefaultEditor and other apps that use the Panels and Accordions but it isn't too late at this point. Actually that wouldn't work for cases like: 
```
<Panel>
   <AnnotationAccordion />
   <Fold />
</Panel>
```
where we wouldn't want `<AnnotationAccordion>` to be a panel itself.

Okay what if the Panel checks for `Accordion` types and then digs into the children of those as well? `Accordion` types could pass props from `Panel` to `Fold` . There is some degree of coupling here though. 

@aulneau you have any thoughts on this?

**Comment by aulneau** [comment]
hmm I wonder if `context` could help here? If panel could contain a collapse function or something in its `context` and then in the fold component we could look for that context, rather than having to traverse / deep look into the children.

**Comment by bpostlethwaite** [comment]
The only issue here is that the Panel needs to know if there are Fold children and how many. If there are none it won't display the Collapse Icon. Ditto for 1. Only when there are 2 or more Folds will the Panel show the collapse button. 2 way information in a 1 way data flow problem... never an elegant solution. 

I guess the least bad is just counting children and because we have Accordions the children of child Accordions...

**Comment by bpostlethwaite** [comment]
Though we could still pass the `toggleFold` function through context. that way there wouldn't be Accordions handing down props... not sure.

**Comment by bpostlethwaite** [comment]
If we are going to root up to 2 levels of children and do something special with Accordions we already have hierarchical constraints 
```
Panel
    Fold
```
or
```
Panel 
    Accordion
        Fold
```
So also coupling together with props doesn't seem so bad. If the components are rendered inside other things we can't count the children and then doesn't matter that the chain of props is also broken.
