### ISSUE TITLE
CSS makes some big assumptions on absolute positioning. 

### ISSUE THREAD

**Issue by bpostlethwaite** [plotly/react-plotly.js-editor#157]
First attempt to throw the simplest Plotly.js + Editor into a create-react-app app.

![image](https://user-images.githubusercontent.com/1176674/33505696-6c3613b6-d6ba-11e7-8693-0a933897e2a4.png)

The Panels have no set width and are positioned `100px` from the right... so if you have a margin...

**Comment by bpostlethwaite** [comment]
I believe this one is addressed now right @VeraZab ?

**Comment by bpostlethwaite** [comment]
Sounds like you have made some updates too @aulneau. What if we edit one of our examples such that the editor appears _within_ a more complicated nested structure? Right now all of our sample apps allow it to take over the screen.

**Comment by aulneau** [comment]
@bpostlethwaite Yeah that sounds like a good idea! I'll whip some examples up. Are there any use cases you know of where it would exist in a nested layout, I was thinking a modal could make sense.

**Comment by bpostlethwaite** [comment]
Sure yes that is a good idea. Another common case will be the canonical bootstrap dashboard layout. nav header and left nav side-panel that toggles inner content views one of which will be the editor and plot.

**Comment by aulneau** [comment]
Cool okay, perfect. I was thinking it might make sense to allow people to change the order of `sidebar` and `panel`. In situations where people might have the editor on the right, we could allow for the sidebar to be flush against the right of the container. But that might be a sep issue.

**Comment by bpostlethwaite** [comment]
yeh could be a sep issue. Another related but separate issue is that I would like a way to programmatically change which panel is open. Specifically some way of putting the bit of state that controls the panel into the Application state rather than the editor state. But yeh I'll make an issue for that specifically.
