### ISSUE TITLE
create all gd.layout UI

### ISSUE THREAD

**Issue by VeraZab** [plotly/react-plotly.js-editor#159]
- [x] Color Bars Panel (z traces), 
- [x] Shapes (fin charts), 
- [ ] GeoJSON (maps)
- [x] Images, 
- [ ] Mobile
- [ ] Calendars
- [ ] Rangeselector Buttons
- [ ] Mapbox special styling options

**Comment by nicolaskruchten** [comment]
Should we make this into a milestone rather than a checklist? I know that Shapes, Color Bars and some others already have issues: #143 #142

**Comment by VeraZab** [comment]
yup, we should.. 

and we should start listing up all of those discrepancies in issues

I just like checklists, so I'm probably just going to keep this one and expand on it anyway
