### ISSUE TITLE
required import of react-select.css isn't great

### ISSUE THREAD

**Issue by bpostlethwaite** [plotly/react-plotly.js-editor#171]
Perhaps we can incorporate the css or host the css in our scss build system? It might be a good idea to incorporate any file copies into the css build step.

**Comment by aulneau** [comment]
@bpostlethwaite I am confused as to why we don't import `import 'react-select/dist/react-select.css';` in the `Dropdown.js` file. What led us to require the import of react-select in the apps versus the `react-plotly.js-editor` source?

**Comment by bpostlethwaite** [comment]
Not sure. It could be that it was added after the fact when it became apparent it was missing and we just starting exporting that convention. 
Seems reasonable to me to put it in Dropdown.js
