### ISSUE TITLE
Editor initializes trace as "line" though chart type selector says "scatter"

### ISSUE THREAD

**Issue by bpostlethwaite** [plotly/react-plotly.js-editor#174]
Ok well it's a "scatter+line" but we should probably treat a "scatter" as a scatter to avoid confusion.

![image](https://user-images.githubusercontent.com/1176674/34161093-72923334-e49d-11e7-8db3-7f783649843f.png)

**Comment by nicolaskruchten** [comment]
I had wondered about this in the past :)
