### ISSUE TITLE
Rename graphDiv -> figure

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/react-plotly.js-editor#178]
IMO it makes for a cleaner-looking external API if at least the editor doesn't advertise itself as expecting a full DOM node :)

**Comment by nicolaskruchten** [comment]
To expand a bit on my proposal: I don't think we should pass in a full DOM node here... We should extract just the references we want, which I believe are `data, layout, _fullLayout, _fullData`, and pass in just that object.

**Comment by VeraZab** [comment]
I believe that for some other workspace functionality that we have, we also need `_fullInput`, my point here is that we never know what plotly.js adds in the future, and maybe leaving it as a full node is a good thing. And it looks familiar because it's a plotly.js - ism.

**Comment by nicolaskruchten** [comment]
OK, what you say makes sense.

**Comment by bpostlethwaite** [comment]
Here is the first docs I hit when doing the most basic search for plotly.js documentation: https://plot.ly/javascript/line-and-scatter/

It uses a string as the graphDiv argument :(

**Comment by nicolaskruchten** [comment]
@bpostlethwaite not sure how to interpret that :)

**Comment by bpostlethwaite** [comment]
A "cheatsheet" I found uses string div IDs and a variable pointing to DOM element named `div`
https://images.plot.ly/plotly-documentation/images/plotly_js_cheat_sheet.pdf

**Comment by bpostlethwaite** [comment]
This "getting started" guide uses a variable called `TESTER` which represents a div with ID `tester`.

Sigh.

It's all over the map but definitely our users are not scared of `<div>`s so it is a good point. There has been talk about removing the `<div>` in Plotly.js 2.0 but I don't know the latest on that.

**Comment by alexcjohnson** [comment]
removing the `<div>`? What do you mean by that? I'd at least be in favor of removing the ability to refer to a `<div>` by its id string...

**Comment by bpostlethwaite** [comment]
Right I suppose I meant discussions on moving away from appending things onto a DOM element.

**Comment by bpostlethwaite** [comment]
obviously we still need a div somewhere :)

**Comment by nicolaskruchten** [comment]
I'm happy to close this issue :)

**Comment by VeraZab** [comment]
yup, I think we can close :)
