### ISSUE TITLE
CSS - allow multiple widgets in widget field

### ISSUE THREAD

**Issue by bpostlethwaite** [plotly/react-plotly.js-editor#183]
Adding this commit cfd7acb broke they styling of Multiple Values
![image](https://user-images.githubusercontent.com/1176674/34362085-6e5dca3e-ea3e-11e7-8c36-5d0d43bf6fc6.png)

**Comment by bpostlethwaite** [comment]
Needed for an application that adds multiple items (looks like this: 
![image](https://user-images.githubusercontent.com/1176674/34362110-9801c534-ea3e-11e7-807e-54fdf9875ee3.png) )

**Comment by aulneau** [comment]
@bpostlethwaite Do you think it makes sense to add that remove functionality you have for the group by fields inside of the editor? I like this display and interactivity of adding multiple fields, it reminds me of adding stops on the uber app.

Do we also want 'Multiple Values' to the select grouping columns section?

**Comment by bpostlethwaite** [comment]
Change it up as you want. We just need to be able to add and remove fields.

I prefer individual rows of groups rather than a single dropdown that can contain multiple values. IMO we want to look fairly standard when built into a native desktop app and not look so web 3.0 as to stick out. But it can and should look great.

**Comment by aulneau** [comment]
fixed via https://github.com/plotly/react-plotly.js-editor/pull/195
