### ISSUE TITLE
Consistent way to override CSS and styling

### ISSUE THREAD

**Issue by bpostlethwaite** [plotly/react-plotly.js-editor#184]
We have style/variables/main.scss which exposes variables users can override to configure the style of the editor. However these styles are consistently applied within the editor. They are not really consistent themselves. 

We need to push more variables into "themable" component scss and expose a more consistent style "API"

I'll have to discuss what is actually required for theming but I think we can go pretty far until I find that info out.

**Comment by aulneau** [comment]
I'm thinking about this... some other components / ui libraries that I've used in the past allow for you to import something like a `ThemeProvider` and then you can pass an obj of style overrides to the component. I think that _might_ work well, I'll have to think about it some more. I also need to refactor a lot of the scss to allow for things to be consistent and abstract enough for everything to work out. Will continue to update this thread as I progress.

**Comment by aulneau** [comment]
So there are a couple options I am thinking about.

If the editor will be _mostly_ used in a sandboxed chromium environment, then I think css variables would be a great way to allow for theming.

For example:

```
:root {
--brand-color: #bababa;
--button-primary-fill: #another
}
```

and then the user could override the styles by including a new definition after they have included the components styles

```
import react-plotly.js-editor/lib/react-plotly.js-editor.css
import styles/plotly.js-editor-custom-theme.css
```

and the `plotly.js-editor-custom-theme.css` could contain one or many new variable definitions that would be applied throughout the application.

The only issue with using css custom props is that they are _not_ super supported:

![screen shot 2017-12-28 at 12 07 20 pm](https://user-images.githubusercontent.com/11803153/34419405-541935d2-ebc9-11e7-9a7e-e4b8bc28057d.png)

Another option would be to use something like [this](https://github.com/javivelasco/react-css-themr), which could also be used if we ever move to [styled-components](https://github.com/styled-components/styled-components)

**Comment by bpostlethwaite** [comment]
The editor will be mostly used in Plotly's Chart Studio. Next will be random installs and apps that depend on the open source lib. But working in a chrome embedded environment is of course a hard requirement.

**Comment by bpostlethwaite** [comment]
The only concerning item in that support document is IE 11 which we support in the Chart Studio. If we can work around that by having the defaults === Chart Studio defaults then that shouldn't be an issue?

**Comment by aulneau** [comment]
Yeah we'd be able to support editor defaults in a way that would just fall back to standard sass variables, and for the embedded / os lib we can do a `@supports` query in css and use css variables. There are also some _potential_ polyfills for it -> https://github.com/webcomponents/shadycss || https://stackoverflow.com/questions/46429913/css-custom-properties-polyfill-for-ie11

I'll have to do some testing. It should work for the meantime.

@VeraZab and I were chatting and we think it would make the most sense for the long term goal to switch over to [styled-components](https://github.com/styled-components/styled-components) in a later phase of the editor.

I think for this phase, I'll explore and try to implement the css custom props, and then after we ship that, we should be talking about if `styled-components` is the direction we want to go 💯

**Comment by bpostlethwaite** [comment]
Okay sounds like a plan!
