### ISSUE TITLE
foldIndex and Key props for Folds seems like an anti-pattern

### ISSUE THREAD

**Issue by bpostlethwaite** [plotly/react-plotly.js-editor#223]
```
          <AxesFold name={_('Range')} foldIndex={1} key={1}>
```

Before we could move blocks of JSX around and they would still work. Now if you move Folds around you have to update `foldIndex` and `key`. That seems like a fairly significant regression.

Any other way?????
@VeraZab @nicolaskruchten @aulneau

**Comment by nicolaskruchten** [comment]
We could give them non-sequential keys, for one thing

**Comment by nicolaskruchten** [comment]
I.e. Strings :)

**Comment by bpostlethwaite** [comment]
That is an improvement. Is there no way for this to be handled automagically? We'll strings if nit. Can someone slamo that in real quick?

**Comment by nicolaskruchten** [comment]
I've been thinking about it and nothing obvious comes to mind. Time to think harder about non-obvious things!

**Comment by bpostlethwaite** [comment]
Sorry that previous comment was autocorrected into obscurity. I'll leave it as is an an amusement.

**Comment by bpostlethwaite** [comment]
Oh seriously. I'll get my laptop on WiFi.

**Comment by bpostlethwaite** [comment]
I am having troubles even adding foldIndexes in a large file. It's hard to keep track of which fold number you should be adding at some particular screenful of code

**Comment by VeraZab** [comment]
see #226 @bpostlethwaite
