### ISSUE TITLE
Axes panel broken

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/react-plotly.js-editor#233]
Clicking on the Axes panel when no traces are loaded causes a full-page blankout, both in dev and 'prod' builds. I initially reported this as a demo/prod-only thing but I now see it in dev also.

**Comment by nicolaskruchten** [comment]
Doesn't happen with v0.4.1, so breakage is recent

**Comment by nicolaskruchten** [comment]
I'm not having a good 24h with bug reports! This is actually not replicable with a clean `node_modules`.

**Comment by aulneau** [comment]
@nicolaskruchten I've had this happen when I am building locally, I've found this can happen with both Axes and Annotations when there are multiple versions of react conflicting.

**Comment by nicolaskruchten** [comment]
OK, glad it's not only me, thanks for sharing :)
