### ISSUE TITLE
Bake AxesSelector into AxesFold

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/react-plotly.js-editor#237]
While writing documentation, I realized things would be cleaner if `<AxesSelector />` were automatically present in `<AxesFold />`. I'm not sure if it ever makes sense to have one without the other. @ben thoughts?

**Comment by nicolaskruchten** [comment]
Hmm, ok so `AxesFold` isn't actually exported, it's connected within DefaultEditor. Maybe we should export it with a built-in selector?

**Comment by nicolaskruchten** [comment]
Broadening the scope of this issue a bit, per the conversation in #230 , I think we should export `LayoutPanel` so as to ⚡️ these two lines https://github.com/plotly/react-plotly.js-editor/blob/master/src/DefaultEditor.js#L36 from both the `DefaultEditor` and any `CustomEditor`

**Comment by nicolaskruchten** [comment]
`LayoutPanel` and `AxesFold` are now exported, but `AxesSelector` still has to be jammed in there manually, so this issue should stay open.

**Comment by nicolaskruchten** [comment]
@VeraZab do you want to try to do this? Would be great if we didn't have to add `AxesSelector` manually in every fold...

**Comment by VeraZab** [comment]
yes!
