### ISSUE TITLE
Legend Panel Zero state

### ISSUE THREAD

**Issue by bpostlethwaite** [plotly/react-plotly.js-editor#241]
When there are no traces it makes little sense to allow legend configuration.

**Comment by bpostlethwaite** [comment]
This one needs to land in production before Jan 18th (Thursday)

**Comment by nicolaskruchten** [comment]
Is this basically going to need a `LegendPanel` that hides itself conditionally?

**Comment by bpostlethwaite** [comment]
Hrm yep probably something like that.

**Comment by aulneau** [comment]
@bpostlethwaite || @nicolaskruchten does it make sense to have any of the style panels enabled when there are no traces?

**Comment by nicolaskruchten** [comment]
The workspace disables them all when you have no traces, so I would say "no, not even layout" on that basis.

**Comment by bpostlethwaite** [comment]
@aulneau can you take this one then?

**Comment by aulneau** [comment]
Yep! Should have a PR this afternoon
