### ISSUE TITLE
Get remaining trace types integrated

### ISSUE THREAD

**Issue by VeraZab** [plotly/react-plotly.js-editor#260]
![screen shot 2018-01-22 at 11 08 15 am](https://user-images.githubusercontent.com/4257572/35230641-9adc0842-ff64-11e7-9b30-47ccf73eefc5.png)

there's 19 chart types left to integrate
@bpostlethwaite @nicolaskruchten if we each take about 6 to integrate, then we'll have all of the current ones of the workspace done.

I'll take the finance ones, tables, and ternary.
@nicolaskruchten @bpostlethwaite which ones could you take?

Checklist:
- [x] error bars
- [x] heatmap
- [x] contour
- [x] ternary
- [x] 3d scatter
- [x] 3d line
- [x] 3d surface
- [x] 3d mesh
- [ ] animation (to look at when we look at mobile breakpoints // aggregations // transforms)
- [ ] timeseries
- [x] candlestick
- [x] ohlc
- [x] histogram
- [x] box plot
- [ ] table (need plotly.js 1.34)
- [x] 2d histogram heatmap
- [x] choropleth
- [x] atlas maps
- [x] satellite maps

**Comment by bpostlethwaite** [comment]
I can take maps!

**Comment by nicolaskruchten** [comment]
I can take the 'z' types and ternary :)

**Comment by nicolaskruchten** [comment]
Are there any other non-obvious dependencies among the chart types? special widgets that certain types share or something?

**Comment by VeraZab** [comment]
there's for sure attributes that the workspace doesn't currently support 'by design' (we just chose not to because that made for a lot of styling options), but I think our strategy now is to _explicitly_ state in the code, which ones we're not displaying to the user.

Still have to see where we do that in the code, but for sure we're going to encounter that.

Alright, thanks guys, we can see how to deal with the rest of chart types as we go, and if one of us sees that someone else has claimed a chart type that it makes more sense to integrate in the batch that we're doing, then we can just ping each other and switch.

**Comment by bpostlethwaite** [comment]
to look up attributes in plotly.js look inside each of these folders `https://github.com/plotly/plotly.js/tree/master/src/traces` for a file called `attributes.js`. If the trace adds special layout attributes it will be in something like a file called `layout_attributes.js`

**Comment by nicolaskruchten** [comment]
I'll grab 3d{scatter, line, mesh} now.

**Comment by VeraZab** [comment]
taking ternary next

**Comment by VeraZab** [comment]
I'm going to take on the 3d's @nicolaskruchten if it's ok with you. That will be another chart type to test with axes.

**Comment by VeraZab** [comment]
doing histogram creation and styling next

**Comment by VeraZab** [comment]
animations now

**Comment by nicolaskruchten** [comment]
in chasing down #293 I went to get some advice from @jackparmer and the conclusion of that discussion was that it was probably a good idea to drop timeseries and animations from the list of "trace types" given that they aren't really trace types and they aren't well-defined in terms of round-tripping from the figure object to UI state and back. I'm very much in favour of this :)

Animations probably should live in its own panel under Create.

**Comment by nicolaskruchten** [comment]
Basically all the commented-out ones here: https://github.com/plotly/react-plotly.js-editor/blob/master/src/components/fields/TraceSelector.js#L20

**Comment by VeraZab** [comment]
> Animations probably should live in its own panel under Create.

That sounds good!

**Comment by VeraZab** [comment]
I'm going to close this and open an issue just for integrating 'tables' which is the only not yet supported chart type by the editor that is currently in the workspace.

(#335)
