### ISSUE TITLE
dev: load saved figures from mocks

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/react-plotly.js-editor#266]
Would be nice to be able to easily preload the dev environment with canned figures e.g. the mocks from plotly.js, so as to see what the editor looks like with various figure configs, without having to actually point'n'click our way through them ;)

**Comment by bpostlethwaite** [comment]
Good idea! The Toolpanel and plotly.js itself have something like this and it's a great fit for the editor. I also liked the Grid in the `lab`. That way we got to push our `dataSources` and data type handling.
I wonder if we could mix and match to get something similar to the workspace's examples+grid
