### ISSUE TITLE
z-type traces: heatmap, surface, contour

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/react-plotly.js-editor#272]
To do for workspace parity:

- [x] Z multi selection
- [x] flip/transpose ?
- [x] heatmap tile trace layout options
- [x] lighting trace layout options
- [x] contour trace layout options
- [x] various axes-related things
- [x] various hover, zoom 3d-related things
- [x] color bar panel #142 
- [x] color scale options #128

**Comment by VeraZab** [comment]
so this one can be closed right?

**Comment by VeraZab** [comment]
oh right, it needs the folds adjustments you were speaking of then it can be closed, correct?
