### ISSUE TITLE
Frames: Animations + Breakpoints features

### ISSUE THREAD

**Issue by VeraZab** [plotly/react-plotly.js-editor#325]

**Comment by jackparmer** [comment]
I think we should hold off / omit the breakpoints feature ("device lab"). I learned last week that the customer we built this for is officially not using it. I'm fairly sure no one but Plotly's blogger is using this feature. 

When/if we re-add device lab, @fabric-8 made this very nice redesign:

https://www.dropbox.com/s/2b8631nadxzu55y/device-lab.mp4?dl=0

*Click-flow on figma here:*
https://www.figma.com/proto/fZWLt6JFr2lKxJNcP3CbCX6m/Streambed?node-id=508%3A62950&scaling=min-zoom

**Comment by VeraZab** [comment]
oh, nice! thanks for the update!
I'll still keep integrating animations into the editor then as a workspace parity goal?
I put both of these features together as they're based on frames, and should be thought about at the same time.

**Comment by nicolaskruchten** [comment]
What features/UI does the current workspace have for animations/frames outside of the mobile/breakpoint stuff?

**Comment by VeraZab** [comment]
there's an animations trace, that's basically a rangeslider you can drag and have it animate your data

**Comment by jackparmer** [comment]
> I'll still keep integrating animations into the editor then as a workspace parity goal?

I think so. Animations have definitely taken off among users. It's nice to brush them up in the GUI even if they were originally created in R or Python.

https://plot.ly/feed/?q=plottype:animation

**Comment by VeraZab** [comment]
great, thanks for the clarification!

**Comment by nicolaskruchten** [comment]
For my own understanding: there is a difference between "sliders" and "rangeslider/rangeselector" right? The "rangeslider/rangeselector" are not related to animations but the "sliders" can be?

And just to clarify what we want to have in the new editor for animations: 
* we still don't want an "animation" trace type, right, for the same reasons as we dropped "time series" and "error bars"?
* we do want some UI around changing/setting sliders and updatemenus?
* we don't want a way for users to be able to actually create frames in the UI?

**Comment by nicolaskruchten** [comment]
(I tried forking and editing one of the animation charts in the feed link you provided, @jackparmer but I couldn't figure out what additional controls appear in the current workspace for these charts... ?)

**Comment by jackparmer** [comment]
> there is a difference between "sliders" and "rangeslider/rangeselector" right?

Yes. Rangslider is for selecting the `range` of an axis. Sliders are general controls that can be used to update really anything in a graph, but are used automatically with animations to switch frames.

Rangeslider: https://plot.ly/javascript/reference/#layout-xaxis-rangeslider

Sliders: https://plot.ly/javascript/reference/#layout-sliders  

> we still don't want an "animation" trace type, right, for the same reasons as we dropped "time series" and "error bars"?

Yes, I think we decided this non-pure trace types were adding too much complexity.

> we do want some UI around changing/setting sliders and updatemenus?

This would be nice, even if it's minimal (like changing the x/y location of existing updatemenus. Alternatively, if we make the `JSONEditor` integration better, power users could change these things through the JSON editor.

> we don't want a way for users to be able to actually create frames in the UI?

Chart Studio can currently autogenerate frames based on selecting an "Animate By" column:

https://help.plot.ly/create-animations/

If there isn't an easy way to replicate this without creating a lot of code complexity, I would vote deferring GUI based frame creation. What would be more useful is if `/external` could open frame-based plots in Chart Studio (currently, if you click "open in plotly" from an animation created in R/Python, Chart Studio can't open it for editing). This is a much bigger deal breaker for animation in Plotly IMO.

> (I tried forking and editing one of the animation charts in the feed link you provided, @jackparmer but I couldn't figure out what additional controls appear in the current workspace for these charts... ?)

I don't think that anything is added. It's impossible to style `layout.updatemenus` or `layout.sliders` in Chart Studio right now.

**Comment by nicolaskruchten** [comment]
OK, this is much clearer to me now, thanks!

So in terms of next steps, I propose we close this issue and create three new ones:

1. Workspace parity around animation features: we should add the "animate by" selector unless it's super-complex.
2. Improvement over workspace: make it such that the new editor can display/edit plots with animations that have been created in R or Python
3. Improvement over workspace: some UX around positioning/styling/etc for updatemenus and sliders  if they already exist in the figure, but not for creating them

Does that capture the independent items around animation?

**Comment by jackparmer** [comment]
👍 Sounds right to me! 

> Improvement over workspace: make it such that the new editor can display/edit plots with animations that have been created in R or Python

I'm fairly sure that `/external` is passing frames through to the frontend, but Chart Studio doesn't currently know how to load them:

https://github.com/plotly/streambed/pull/9445

**Comment by nicolaskruchten** [comment]
So if I click on the "edit in Chart Studio" button on the first chart here https://plot.ly/javascript/gapminder-example/ it looks like it makes its way into the Chart Studio OK, and the JSON editor shows that the frames are there etc, but then there are some issues like saving doesn't seem to work and the actual animation doesn't run. Is that what you mean by "doesn't know how to load them"?
