### ISSUE TITLE
Strip out tags in title displays

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/react-plotly.js-editor#341]
We display trace names as Fold titles and axis names in dropdowns, and we should strip out tags when we do, perhaps using https://www.npmjs.com/package/striptags

![image](https://user-images.githubusercontent.com/203523/36485364-0b5d9f30-16ea-11e8-9cd8-42de416fb1ce.png)

![image](https://user-images.githubusercontent.com/203523/36485388-1be31d30-16ea-11e8-80bb-910ff7909bb4.png)

**Comment by nicolaskruchten** [comment]
@VeraZab what do you think of https://www.npmjs.com/package/striptags ? Do we have a different library we use for this sort of thing? Something built in to plotly.js?

**Comment by VeraZab** [comment]
Striptags looks good, let's use that if plotly.js doesn't have anything built in. (cc @alexcjohnson we don't have anything in plotly.js doing this correct?)

**Comment by alexcjohnson** [comment]
We do have [`svgTextUtils.plainText`](https://github.com/plotly/plotly.js/blob/master/src/lib/svg_text_utils.js#L273) - which has the distinction of only stripping the tags that plotly.js actually supports. I *think* that means the results will be more consistent with what you see on the actual plot, in case someone uses an unsupported tag.

**Comment by VeraZab** [comment]
oh nice! Then I think it'd be a good idea @nicolaskruchten to use svgTextUtils. All the places we allow the user to use html tags is because it's an input to plotly.js afaik..

**Comment by nicolaskruchten** [comment]
Hmmm, this seems less safe than the NPM module which isn't regex-based...

**Comment by alexcjohnson** [comment]
> Hmmm, this seems less safe than the NPM module which isn't regex-based...

Does that mean there's a bug in plotly.js? That we should fix (possibly by using the npm module) and then use it here too?

**Comment by nicolaskruchten** [comment]
I don't know if there's a bug in plotly.js, just that regex-based tag sanitizers are sometimes considered less safe than simpler state-machine-based ones... See this for example: https://stackoverflow.com/questions/24723/best-regex-to-catch-xss-cross-site-scripting-attack-in-java/535022#535022

**Comment by nicolaskruchten** [comment]
For example:

`plainText("<<a>script>alert('ciao');<</a>/script>")` 
returns 
`'< script>alert(\'ciao\');< /script>'`

**Comment by alexcjohnson** [comment]
Fair enough - though I'm not concerned about XSS as far as `plainText` is concerned, we don't use its output as HTML but as text... so the would-be attacker will see some ugly "text" just as they will within plotly.js, but won't hurt anyone.
![screen shot 2018-02-21 at 3 13 34 pm](https://user-images.githubusercontent.com/2678795/36503052-e11ec48a-1719-11e8-89fc-f691d7e2d434.png)

**Comment by nicolaskruchten** [comment]
Ahhh right ok, I was stuck in an XSS frame here because of what I was doing this morning, but that's not what we're talking about, either in plotly.js or in the editor: we do in fact want to safely render text just the way plotly.js would, so there's "no risk" of XSS here anyway because we wouldn't be using `dangerouslySetInnerHTML`. OK, I'll use this then. Shall I load it directly from that file or is it available on the `Plotly` object somewhere?

**Comment by alexcjohnson** [comment]
I don't think it's exposed on the `Plotly` object, no.

**Comment by nicolaskruchten** [comment]
I opted for `striptags` in the end because `plainText` seems to insert spaces at the tag boundaries... NBD either way :)
