### ISSUE TITLE
immutability-helper dependency is missing

### ISSUE THREAD

**Issue by vdh** [plotly/react-plotly.js-editor#343]
[Panel.js](https://github.com/plotly/react-plotly.js-editor/blob/a061c56465271ccf933fcde4f1d5c33f1c2e4ffa/src/components/containers/Panel.js) uses `immutability-helper`, but it's only listed in `devDependencies`, so it doesn't get installed.

**Comment by nicolaskruchten** [comment]
Thanks for letting us know! Fix will be in master shortly.
